services:
  pgsql:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data:
